name: Update Medium Feed

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Fetch Medium RSS feed
        run: |
          curl -s "https://medium.com/feed/@DaiMika" > medium.xml
          python3 - <<EOF
import xml.etree.ElementTree as ET, yaml, datetime
tree = ET.parse('medium.xml')
root = tree.getroot()
items = []
for item in root.findall('./channel/item')[:5]:
    title = item.find('title').text
    link = item.find('link').text
    pubDate = item.find('pubDate').text
    items.append({'title': title, 'link': link, 'pubDate': pubDate})
with open('_data/medium_feed.yml', 'w') as f:
    yaml.dump({'items': items, 'updated': datetime.datetime.utcnow().isoformat()}, f)
EOF
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add _data/medium_feed.yml
          git commit -m "Update Medium feed"
          git push

